// <auto-generated />
using System;
using EduTroca.Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduTroca.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConteudoUsuario", b =>
                {
                    b.Property<Guid>("LikesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LikesId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LikesId", "LikesId1");

                    b.HasIndex("LikesId1");

                    b.ToTable("Likes", (string)null);
                });

            modelBuilder.Entity("ConteudoUsuario1", b =>
                {
                    b.Property<Guid>("DislikesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DislikesId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DislikesId", "DislikesId1");

                    b.HasIndex("DislikesId1");

                    b.ToTable("Dislikes", (string)null);
                });

            modelBuilder.Entity("EduTroca.Core.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("EduTroca.Core.Entities.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConteudoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("ConteudoId");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("EduTroca.Core.Entities.ConteudoAggregate.Conteudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Visualizacoes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Conteudos", (string)null);

                    b.HasDiscriminator<int>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EduTroca.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a4ab49c-5036-4316-b2f6-c2e8fac39705"),
                            Code = 1,
                            Nome = "Admin"
                        },
                        new
                        {
                            Id = new Guid("c999156a-c73e-49b2-9789-ed7e28f1afe7"),
                            Code = 2,
                            Nome = "User"
                        },
                        new
                        {
                            Id = new Guid("7ae60301-fa05-4512-9361-387262ea60b4"),
                            Code = 3,
                            Nome = "Owner"
                        });
                });

            modelBuilder.Entity("EduTroca.Core.Entities.UsuarioAggregate.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CaminhoImagem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RoleUsuario", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("UsuarioCategorias", b =>
                {
                    b.Property<Guid>("CategoriasDeInteresseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InteressadosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriasDeInteresseId", "InteressadosId");

                    b.HasIndex("InteressadosId");

                    b.ToTable("UsuarioCategorias");
                });

            modelBuilder.Entity("EduTroca.Core.Entities.ConteudoAggregate.Pergunta", b =>
                {
                    b.HasBaseType("EduTroca.Core.Entities.ConteudoAggregate.Conteudo");

                    b.Property<string>("TextoCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("EduTroca.Core.Entities.ConteudoAggregate.Video", b =>
                {
                    b.HasBaseType("EduTroca.Core.Entities.ConteudoAggregate.Conteudo");

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaminhoVideo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("ConteudoUsuario", b =>
                {
                    b.HasOne("EduTroca.Core.Entities.ConteudoAggregate.Conteudo", null)
                        .WithMany()
                        .HasForeignKey("LikesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTroca.Core.Entities.UsuarioAggregate.Usuario", null)
                        .WithMany()
                        .HasForeignKey("LikesId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConteudoUsuario1", b =>
                {
                    b.HasOne("EduTroca.Core.Entities.ConteudoAggregate.Conteudo", null)
                        .WithMany()
                        .HasForeignKey("DislikesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTroca.Core.Entities.UsuarioAggregate.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DislikesId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduTroca.Core.Entities.Comentario", b =>
                {
                    b.HasOne("EduTroca.Core.Entities.UsuarioAggregate.Usuario", "Autor")
                        .WithMany("Comentarios")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduTroca.Core.Entities.ConteudoAggregate.Conteudo", "Conteudo")
                        .WithMany("Comentarios")
                        .HasForeignKey("ConteudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Conteudo");
                });

            modelBuilder.Entity("EduTroca.Core.Entities.ConteudoAggregate.Conteudo", b =>
                {
                    b.HasOne("EduTroca.Core.Entities.UsuarioAggregate.Usuario", "Autor")
                        .WithMany("Conteudos")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduTroca.Core.Entities.Categoria", "Categoria")
                        .WithMany("Conteudos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EduTroca.Core.Entities.UsuarioAggregate.Usuario", b =>
                {
                    b.OwnsOne("EduTroca.Core.Entities.UsuarioAggregate.EmailConfirmationCode", "EmailConfirmationCode", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("UsedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("UsuarioId")
                                .IsUnique();

                            b1.ToTable("EmailConfirmationCode", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsMany("EduTroca.Core.Entities.UsuarioAggregate.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOnUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("UsuarioId");

                            b1.ToTable("RefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("EmailConfirmationCode")
                        .IsRequired();

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("RoleUsuario", b =>
                {
                    b.HasOne("EduTroca.Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTroca.Core.Entities.UsuarioAggregate.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UsuarioCategorias", b =>
                {
                    b.HasOne("EduTroca.Core.Entities.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasDeInteresseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTroca.Core.Entities.UsuarioAggregate.Usuario", null)
                        .WithMany()
                        .HasForeignKey("InteressadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduTroca.Core.Entities.Categoria", b =>
                {
                    b.Navigation("Conteudos");
                });

            modelBuilder.Entity("EduTroca.Core.Entities.ConteudoAggregate.Conteudo", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("EduTroca.Core.Entities.UsuarioAggregate.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Conteudos");
                });
#pragma warning restore 612, 618
        }
    }
}
